// The one Habr Career profile as a proposal (generated by `sgz habr-resume`, never auto-written) and the
// edit-page writer used only by `sgz habr-resume --apply` after the human approved the proposal.
// Edit pages are classic Rails forms (2026-09 recordings):
//   /profile/specialization  #user_resume_headline (maxlength 80), user[raw_specialization_ids][] (max 2),
//                            #user_salary_qualification_id (1 Intern, 3 Junior, 4 Middle, 5 Senior, 6 Lead),
//                            user[user_skills_ids][] hidden inputs (max 30; ids from /api/frontend/suggestions/skills?term=)
//   /profile/personal/edit   #user_about (redactor: hidden textarea + .redactor-in contenteditable)
//   /profile/experiences     /profile/experiences/<id>/edit → #experience_description (redactor)
import type { BrowserSession, Profile } from "@sgz/shared";
import { claimRegex, stripNeverClaimSentences } from "../llm/guards.js";
import { HABR_ORIGIN, extractSsrState, loginFromHeader, parseExperiences, parseResumeState, type HabrResumeState } from "./state.js";

export const MAX_SKILLS = 30;
export const MAX_TITLE = 80;
export const QUALIFICATIONS: Record<string, number> = { Junior: 3, Middle: 4, Senior: 5 };
/** Development group of Habr specializations (id → title); a profile holds at most 2. */
export const SPECIALIZATIONS: Record<number, string> = { 2: "Бэкенд разработчик", 3: "Фронтенд разработчик", 4: "Фулстек разработчик", 82: "Веб-разработчик", 72: "Разработчик приложений" };

export interface HabrResumeProposal {
  title: string;
  specializations: number[];
  qualification: "Junior" | "Middle" | "Senior";
  about: string;
  skills: string[];
  experiences: { company: string; description: string }[];
  notes: string[];
}

const norm = (s: string): string => s.toLowerCase().replace(/\.js\b/g, "").replace(/[^a-zа-яё0-9+#]+/gi, "");
const ALIASES: Record<string, string> = { golang: "go", postgres: "postgresql", vuejs: "vue", reactjs: "react", nextjs: "next", nodejs: "node", k8s: "kubernetes" };
const canon = (s: string): string => ALIASES[norm(s)] ?? norm(s);
const words = (s: string): string[] => s.toLowerCase().split(/[^a-zа-яё0-9+#]+/i).filter(Boolean);
const within = (a: string[], b: string[]): boolean => a.length > 0 && a.every((x) => b.includes(x));
/** Habr's dictionary spells a few skills out. */
const SEARCH_AS: Record<string, string> = { ssr: "Server-side rendering" };

/**
 * Keeps the proposal inside the facts: skills only from `allowed` (verified_skills + the base CVs' stacks)
 * and never from never_claim, at most 30; title ≤ 80; specializations from the known list, at most 2;
 * experiences only for companies Habr already has. Returns what was dropped as notes.
 */
export function guardProposal(p: HabrResumeProposal, allowed: string[], profile: Pick<Profile, "never_claim_skills">, habrCompanies: string[]): HabrResumeProposal {
  const ok = new Set(allowed.map(canon));
  const never = claimRegex(profile.never_claim_skills);
  const notes = [...(p.notes ?? [])];
  const seen = new Set<string>();
  const skills: string[] = [];
  for (const raw of p.skills ?? []) {
    const s = raw.trim();
    const k = canon(s);
    if (!s || seen.has(k)) continue;
    seen.add(k);
    if (!ok.has(k) || never?.test(s)) {
      notes.push(`guard: навык «${s}» убран - его нет в verified_skills и базовых резюме`);
      continue;
    }
    skills.push(s);
  }
  // Free text claims too: a never_claim skill in «о себе» or a job description loses its sentence.
  const clean = (text: string, where: string): string => {
    const t = stripNeverClaimSentences(text.trim(), profile.never_claim_skills);
    if (t !== text.trim()) notes.push(`guard: из «${where}» убраны предложения с навыками из never_claim`);
    return t;
  };
  const known = new Set(habrCompanies.map((c) => c.trim().toLowerCase()));
  const experiences = (p.experiences ?? [])
    .filter((e) => {
      const hit = known.has(e.company.trim().toLowerCase());
      if (!hit) notes.push(`guard: опыт «${e.company}» убран - такого места работы нет в профиле на Хабре`);
      return hit;
    })
    .map((e) => ({ ...e, description: clean(e.description, `опыт ${e.company}`) }))
    .filter((e) => e.description);
  return {
    title: p.title.trim().slice(0, MAX_TITLE),
    specializations: [...new Set(p.specializations ?? [])].filter((id) => id in SPECIALIZATIONS).slice(0, 2),
    qualification: p.qualification in QUALIFICATIONS ? p.qualification : "Middle",
    about: clean(p.about, "о себе"),
    skills: skills.slice(0, MAX_SKILLS),
    experiences,
    notes,
  };
}

/**
 * Maps skill names to Habr's skill dictionary titles (public GET /api/frontend/suggestions/skills?term=),
 * exact, alias (Go → Golang) or a narrower title (REST API → REST). Unknown names come back in `missing`, and
 * names Habr only has in a wider title (SQL → Microsoft SQL Server) in `wider`: that title is a different,
 * unverified claim, so it is only suggested. Runs after guardProposal: the titles are checked against
 * never_claim_skills again by the caller. The order is kept.
 */
export async function resolveHabrSkills(names: string[], get: (url: string) => Promise<{ list?: { title: string }[] }>): Promise<{ skills: string[]; missing: string[]; wider: { name: string; title: string }[] }> {
  const skills: string[] = [];
  const missing: string[] = [];
  const wider: { name: string; title: string }[] = [];
  for (const name of names) {
    const term = SEARCH_AS[norm(name)] ?? name;
    const r = await get(`${HABR_ORIGIN}/api/frontend/suggestions/skills?term=${encodeURIComponent(term)}`).catch(() => ({ list: [] }));
    const list = r.list ?? [];
    const w = words(term);
    // Exact, then alias (Go ~ Golang), then a title whose words are all in the name (REST API ~ REST).
    const hit =
      list.find((x) => x.title.toLowerCase() === term.toLowerCase()) ??
      list.find((x) => canon(x.title) === canon(name)) ??
      list.find((x) => within(words(x.title), w));
    const wide = hit ? undefined : list.find((x) => within(w, words(x.title)));
    if (hit) {
      if (!skills.includes(hit.title)) skills.push(hit.title);
    } else if (wide) wider.push({ name, title: wide.title });
    else missing.push(name);
  }
  return { skills, missing, wider };
}

/** Human-readable proposal for the terminal / the orchestrator. */
export function renderProposal(p: HabrResumeProposal): string {
  return [
    `Заголовок: ${p.title}`,
    `Специализации: ${p.specializations.map((id) => SPECIALIZATIONS[id] ?? id).join(", ")}`,
    `Квалификация: ${p.qualification}`,
    `Навыки (${p.skills.length}): ${p.skills.join(", ")}`,
    "",
    "О себе:",
    p.about,
    ...p.experiences.flatMap((e) => ["", `Опыт - ${e.company}:`, e.description]),
    ...(p.notes.length ? ["", "Заметки:", ...p.notes.map((n) => `- ${n}`)] : []),
  ].join("\n");
}

/** Plain text (paragraphs, «- » lines) → the HTML the redactor fields store. */
export function toRedactorHtml(text: string): string {
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return text
    .trim()
    .split(/\n\s*\n/)
    .map((para) => `<p>${para.split("\n").map((l) => esc(l.trim())).join("<br>")}</p>`)
    .join("");
}

/** What the Habr profile holds today (public resume page state) + the experience edit ids. */
export async function readHabrProfile(s: BrowserSession): Promise<{ login: string; resume: HabrResumeState; experiences: { id: string; company: string }[] }> {
  await s.goto(`${HABR_ORIGIN}/profile/experiences`);
  const html = await s.html();
  const login = loginFromHeader(html);
  if (!login) throw new Error("Habr Career: not logged in (run sgz habr-login)");
  let experiences = parseExperiences(html);
  await s.goto(`${HABR_ORIGIN}/${login}`, { quick: true });
  const resume = parseResumeState(extractSsrState(await s.html()));
  // Both pages list the places in the same order; the resume state has the exact company titles.
  if (resume.companies.length === experiences.length) experiences = experiences.map((e, i) => ({ ...e, company: resume.companies[i]!.title }));
  return { login, resume, experiences };
}

// Sets a redactor-backed textarea: the hidden textarea is what the form posts, the contenteditable is what
// redactor would sync back into it, so both get the same HTML.
const setRedactorJs = (selector: string, html: string): string => `(() => {
  const ta = document.querySelector(${JSON.stringify(selector)});
  if (!ta) return false;
  const box = ta.closest(".redactor-box") || ta.parentElement;
  const ed = box && box.querySelector(".redactor-in");
  if (ed) ed.innerHTML = ${JSON.stringify(html)};
  ta.value = ${JSON.stringify(html)};
  ta.dispatchEvent(new Event("change", { bubbles: true }));
  return true;
})()`;

const submitFormOf = (selector: string): string => `(() => {
  const el = document.querySelector(${JSON.stringify(selector)});
  const form = el && el.closest("form");
  const btn = form && form.querySelector('input[type="submit"][name="commit"], button[type="submit"]');
  if (!btn) return false;
  btn.click();
  return true;
})()`;

/** The experience edit form is data-remote (rails-ujs adds the CSRF header) and Habr's hh-imported jobs have its
 * required specialization/qualification blank: posted as is it fails silently. This posts it itself, fills
 * only the blank required fields, and returns the server's answer. */
export const saveExperienceJs = (id: string, html: string, spec: string, qual: string): string => `(async () => {
  const f = document.querySelector("#edit_experience_" + ${JSON.stringify(id)});
  if (!f) return { status: 0, body: "no form", filled: [] };
  const fd = new FormData(f);
  fd.set("experience[description]", ${JSON.stringify(html)});
  const filled = [];
  if (!fd.get("experience[specialization_id]")) { fd.set("experience[specialization_id]", ${JSON.stringify(spec)}); filled.push("specialization"); }
  if (!fd.get("experience[qualification_id]")) { fd.set("experience[qualification_id]", ${JSON.stringify(qual)}); filled.push("qualification"); }
  const token = document.querySelector("meta[name=csrf-token]");
  const r = await fetch(f.action, { method: "POST", body: fd, credentials: "include", headers: { "X-CSRF-Token": token ? token.content : "", "X-Requested-With": "XMLHttpRequest", Accept: "text/javascript, application/json" } });
  return { status: r.status, body: (await r.text()).slice(0, 300), filled };
})()`;

/** A 2xx answer without Rails' validation markup. */
export const experienceSaved = (r: { status: number; body: string }): boolean =>
  r.status >= 200 && r.status < 300 && !/error|ошибк|не может быть пуст|can't be blank/i.test(r.body);

const sameStart = (a: string, b: string): boolean => {
  const n = (s: string) => s.replace(/\s+/g, " ").trim().slice(0, 40);
  return n(a) === n(b);
};

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

/**
 * Writes an approved proposal to the Habr profile. Only called by `sgz habr-resume --apply`. Each page is
 * verified after saving; the returned lines say what was written and what could not be.
 */
export async function writeHabrProfile(s: BrowserSession, p: HabrResumeProposal, settleMs = 2500): Promise<string[]> {
  const out: string[] = [];
  const { login, experiences } = await readHabrProfile(s);

  // 1. Specialization page: headline, specializations, qualification, skills.
  await s.goto(`${HABR_ORIGIN}/profile/specialization`);
  const specJs = `(async () => {
    const f = document.querySelector("#user_resume_headline").closest("form");
    const want = ${JSON.stringify(p.skills)};
    const ids = [];
    const missing = [];
    for (const name of want) {
      const r = await fetch("/api/frontend/suggestions/skills?term=" + encodeURIComponent(name), { credentials: "include" });
      const list = r.ok ? (await r.json()).list || [] : [];
      const hit = list.find((x) => x.title.toLowerCase() === name.toLowerCase());
      if (hit && !ids.includes(hit.value)) ids.push(hit.value); else if (!hit) missing.push(name);
    }
    const h = document.querySelector("#user_resume_headline");
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set.call(h, ${JSON.stringify(p.title)});
    h.dispatchEvent(new Event("input", { bubbles: true }));
    const q = document.querySelector("#user_salary_qualification_id");
    q.value = ${JSON.stringify(String(QUALIFICATIONS[p.qualification]))};
    q.dispatchEvent(new Event("change", { bubbles: true }));
    const specs = ${JSON.stringify(p.specializations.map(String))};
    for (const cb of f.querySelectorAll('input[name="user[raw_specialization_ids][]"]')) if (cb.checked && !specs.includes(cb.value)) cb.click();
    for (const cb of f.querySelectorAll('input[name="user[raw_specialization_ids][]"]')) if (!cb.checked && specs.includes(cb.value)) cb.click();
    for (const i of f.querySelectorAll('input[name="user[user_skills_ids][]"]')) i.disabled = true;
    for (const id of ids.slice(0, ${MAX_SKILLS})) {
      const i = document.createElement("input");
      i.type = "hidden"; i.name = "user[user_skills_ids][]"; i.value = String(id);
      f.appendChild(i);
    }
    f.querySelector('input[type="submit"][name="commit"]').click();
    return { ids: ids.length, missing };
  })()`;
  const spec = await s.evaluate<{ ids: number; missing: string[] }>(specJs);
  await sleep(settleMs);
  await s.goto(`${HABR_ORIGIN}/profile/specialization`, { quick: true });
  const saved = extractSsrState(await s.html()) as { selectedSkills?: { title: string }[] };
  out.push(`специализация/навыки: сохранено ${saved.selectedSkills?.length ?? 0} навыков из ${spec.ids}${spec.missing.length ? `; нет в словаре Хабра: ${spec.missing.join(", ")}` : ""}`);

  // 2. About.
  await s.goto(`${HABR_ORIGIN}/profile/personal/edit`);
  if (await s.evaluate<boolean>(setRedactorJs("#user_about", toRedactorHtml(p.about)))) {
    await s.evaluate(submitFormOf("#user_about"));
    await sleep(settleMs);
    out.push("о себе: сохранено");
  } else out.push("о себе: поле #user_about не найдено");

  // 3. Experiences, matched by company name to the entries Habr already has (never creates new ones).
  for (const e of p.experiences) {
    const target = experiences.find((x) => x.company.trim().toLowerCase() === e.company.trim().toLowerCase());
    if (!target) {
      out.push(`опыт «${e.company}»: на Хабре нет такого места, пропущено`);
      continue;
    }
    await s.goto(`${HABR_ORIGIN}/profile/experiences/${target.id}/edit`);
    const spec = String(p.specializations[0] ?? 4);
    const qual = String(QUALIFICATIONS[p.qualification]);
    const r = (await s.evaluate<{ status: number; body: string; filled: string[] } | null>(saveExperienceJs(target.id, toRedactorHtml(e.description), spec, qual))) ?? { status: 0, body: "no result", filled: [] };
    const filled = r.filled.length ? ` (пустые обязательные поля заполнены: ${r.filled.map((f) => (f === "qualification" ? `квалификация ${p.qualification}` : `специализация ${SPECIALIZATIONS[Number(spec)] ?? spec}`)).join(", ")})` : "";
    out.push(experienceSaved(r) ? `опыт «${e.company}»: отправлено${filled}` : `опыт «${e.company}»: НЕ сохранено (HTTP ${r.status}: ${r.body.replace(/\s+/g, " ").slice(0, 160)})`);
    await sleep(settleMs);
  }

  // Verify from the public resume page.
  await s.goto(`${HABR_ORIGIN}/${login}`, { quick: true });
  const now = parseResumeState(extractSsrState(await s.html()));
  const aboutOk = now.about.slice(0, 40) === p.about.replace(/\s+/g, " ").trim().slice(0, 40) || now.about.includes(p.about.split("\n")[0]!.slice(0, 40));
  out.push(`проверка: о себе ${aboutOk ? "совпадает" : "НЕ совпадает"}, навыков ${now.skills.length}, мест работы ${now.companies.length}`);
  for (const e of p.experiences) {
    const c = now.companies.find((x) => x.title.trim().toLowerCase() === e.company.trim().toLowerCase());
    if (c) out.push(`проверка: опыт «${e.company}» ${sameStart(c.description, e.description) ? "совпадает" : "НЕ совпадает"}`);
  }
  return out;
}
