#!/usr/bin/env bash
# Regenerates packages/server/src/career/ats/sites/index.ts from the client files in that folder.
set -euo pipefail
dir="$(cd "$(dirname "$0")/.." && pwd)/packages/server/src/career/ats/sites"
out="$dir/index.ts"
{
  echo '// One client per company careers site (kind "site:<slug>"). Generated by scripts/gen-site-clients.sh.'
  echo 'import type { ATSClientImpl } from "../types.js";'
  names=()
  for f in "$dir"/*.ts; do
    slug="$(basename "$f" .ts)"
    [ "$slug" = index ] && continue
    name="c_$(echo "$slug" | tr -c 'a-zA-Z0-9\n' '_')"
    echo "import { client as $name } from \"./$slug.js\";"
    names+=("$name")
  done
  echo
  echo "export const siteClients: ATSClientImpl[] = [$(IFS=,; echo "${names[*]:-}" | sed 's/,/, /g')];"
} > "$out"
echo "wrote $out (${#names[@]} clients)"
