#!/usr/bin/env bash
# Ship the gitignored data/ dir (profiles, cookies, CVs, TeX class, .env) from the Mac to the Pi.
# Usage: scripts/sync-data.sh        PI_HOST=rpi-ts  PI_DATA=/opt/sgz/data  SGZ_LOCAL_DATA=./data
#
# Never deletes anything on the Pi (the Pi owns its DB, snapshots, generated resumes, browser profiles).
# Excluded: sgz.db* (Pi has its own), snapshots/, chrome-profile*/ and action-cache/ (per-machine),
#           recordings/, generated/, backups/, logs. Included: users/*/{profile.yaml,hh-cookies.json,cv/}, tex/.
# .env is rewritten for the Pi: SGZ_DATA_DIR/SGZ_REPO_DIR are dropped (systemd's EnvironmentFile would
# otherwise override the unit's /opt/sgz paths) and the binaries are pinned. data/.env.pi (optional,
# gitignored) is appended last for Pi-only overrides, e.g. SGZ_RUNNER=false.
set -euo pipefail

PI_HOST="${PI_HOST:-rpi-ts}"
PI_DATA="${PI_DATA:-/opt/sgz/data}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${SGZ_LOCAL_DATA:-$ROOT/data}"
[[ -d "$SRC" ]] || { echo "no local data dir at $SRC" >&2; exit 1; }
[[ -f "$SRC/.env" ]] || echo "note: $SRC/.env missing - copy data.example/.env.example to data/.env first" >&2

step() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }

step "rsync $SRC/ -> $PI_HOST:$PI_DATA/ (no --delete)"
ssh "$PI_HOST" "mkdir -p '$PI_DATA'"
rsync -az \
  --exclude 'sgz.db' --exclude 'sgz.db-*' --exclude '*.db' --exclude '*.db-*' \
  --exclude 'snapshots' --exclude 'chrome-profile*' --exclude 'action-cache' --exclude 'recordings' \
  --exclude 'generated' --exclude 'backups' --exclude '*.log' --exclude '.DS_Store' \
  --exclude '.env' --exclude '.env.*' \
  "$SRC/" "$PI_HOST:$PI_DATA/"

if [[ -f "$SRC/.env" ]]; then
  step "write $PI_DATA/.env for the Pi"
  tmp="$(mktemp "${TMPDIR:-/tmp}/sgz-env.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT
  {
    echo "# generated by scripts/sync-data.sh from data/.env on $(date -u +%Y-%m-%dT%H:%M:%SZ) - edit data/.env (+ data/.env.pi) on the Mac instead"
    grep -vE '^[[:space:]]*(SGZ_DATA_DIR|SGZ_REPO_DIR|CHROMIUM_BIN|CLAUDE_BIN|XELATEX_BIN)=' "$SRC/.env"
    echo "CHROMIUM_BIN=/usr/bin/chromium"
    echo "CLAUDE_BIN=/usr/local/bin/claude"
    # XELATEX_BIN is the frozen config name for the LaTeX engine; the CV class is pdflatex-only.
    echo "XELATEX_BIN=/usr/bin/pdflatex"
    if [[ -f "$SRC/.env.pi" ]]; then
      echo "# --- data/.env.pi overrides ---"
      cat "$SRC/.env.pi"
    fi
  } > "$tmp"
  rsync -az "$tmp" "$PI_HOST:$PI_DATA/.env"
fi

step "permissions on the Pi"
ssh "$PI_HOST" "chmod 750 '$PI_DATA'; chmod 600 '$PI_DATA/.env' 2>/dev/null; find '$PI_DATA/users' -name 'hh-cookies*.json' -exec chmod 600 {} + 2>/dev/null; ls -la '$PI_DATA' '$PI_DATA/users' 2>/dev/null | sed 's/^/  /'"
echo
echo "done. If .env changed: ssh $PI_HOST sudo systemctl restart sgz"
